In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
## your code
pows = np.arange(1, 21)
ans = (2 * np.ones((20,)))**pows / pows
ans

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
## your code
n = 5
pow1 = 3*np.arange(1, n + 1)
pow2 = 4*np.arange(1, n + 1)
np.sum((0.1 * np.ones((n,)))**pow1 * (0.2 * np.ones((n,))) ** pow2)

1.6000025600040968e-06

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
## your code
z = np.zeros((8, 8))
o = np.arange(0, 8, 2)
c = np.arange(1, 8, 2)
z[o, :] = np.arange(0, 8) % 2
z[c, :] = np.arange(1, 9) % 2
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))

## your code
r = np.sum(X ** 2, axis=1) ** 0.5
X[:,1] = np.arcsin(X[:,1]/r)
X[:,0] = r
X

array([[1.16883009, 0.71670802],
       [0.30451811, 0.90992002],
       [0.80228539, 1.11070368],
       [0.74085459, 1.42284516],
       [0.96952152, 1.13530263]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.randint(0, 30, (10, 10))

x, y = np.where(X == X.flat[np.argmax(X)])
list(zip(x,y)), X

([(2, 5), (3, 4), (4, 5), (7, 7)],
 array([[14,  3,  4,  0,  2, 25, 13,  0,  2, 15],
        [ 5, 19, 21,  1, 22,  5,  9, 12, 24,  4],
        [ 7, 24,  6,  0, 27, 29, 11, 20, 21,  6],
        [18,  7, 14, 25, 29,  2,  3, 26, 26, 17],
        [17,  7, 11, 26, 14, 29, 24, 12, 18,  6],
        [17, 10, 20, 22, 26, 16,  5,  2,  9, 25],
        [ 5,  2,  9, 21, 28, 28, 26, 20, 14, 13],
        [19, 28,  9, 19, 28, 15, 13, 29,  6,  0],
        [ 0, 11,  1,  6, 10, 17, 18, 19, 24, 13],
        [20, 17, 21, 19,  6, 18, 23,  9, 21, 16]]))

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X, y, X[np.argmin(np.sum((X-y) ** 2, axis=1)), :]

(array([[0.2936384 , 0.36003604],
        [0.93944132, 0.84680396],
        [0.74586   , 0.27966083],
        [0.62660881, 0.71871274],
        [0.15927026, 0.82662201],
        [0.21576048, 0.95516775],
        [0.71627797, 0.51765209],
        [0.2811295 , 0.8840861 ],
        [0.20485455, 0.4801915 ],
        [0.75620567, 0.2616522 ]]),
 array([[0.8912429 , 0.73926829]]),
 array([0.93944132, 0.84680396]))

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
## your code
def f(x):
    if x < 0:
        return x ** 2 + 2*x + 6
    if 0 <= x <= 2:
        return x  + 6
    if x >= 2:
        return x ** 2 + 4*x-4

x = np.linspace(-3, 3, 100)

list(map(f, x))

[9.0,
 8.761248852157943,
 8.529843893480258,
 8.305785123966942,
 8.089072543617998,
 7.879706152433425,
 7.677685950413223,
 7.483011937557392,
 7.295684113865932,
 7.115702479338843,
 6.943067033976125,
 6.777777777777777,
 6.619834710743801,
 6.469237832874196,
 6.325987144168962,
 6.190082644628099,
 6.061524334251607,
 5.940312213039485,
 5.8264462809917354,
 5.719926538108356,
 5.620752984389348,
 5.528925619834711,
 5.444444444444445,
 5.367309458218549,
 5.297520661157025,
 5.235078053259871,
 5.179981634527089,
 5.132231404958677,
 5.0918273645546375,
 5.058769513314968,
 5.033057851239669,
 5.014692378328742,
 5.003673094582186,
 5.0,
 5.003673094582186,
 5.014692378328742,
 5.033057851239669,
 5.058769513314968,
 5.0918273645546375,
 5.132231404958678,
 5.179981634527089,
 5.235078053259872,
 5.297520661157025,
 5.367309458218549,
 5.444444444444445,
 5.528925619834711,
 5.620752984389348,
 5.719926538108356,
 5.8264462809917354,
 5.940312213039486,
 6.03030303030303,
 6.09

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))

(X.T - X.mean(axis=1)).T, (X.T - X.mean(axis=1)).T.mean(axis=1)

(array([[-0.34481407,  0.15139134,  0.14689841,  0.00371404,  0.15396756,
          0.18918087, -0.35493744,  0.4069421 ,  0.00070461, -0.35304742],
        [-0.13765835, -0.20129105, -0.21466196,  0.02443593, -0.08218078,
          0.44976011,  0.29604143, -0.27745793, -0.39011556,  0.53312816],
        [ 0.29764892, -0.44805321, -0.47327922,  0.30171487,  0.43637136,
         -0.05461647, -0.04152341,  0.2582934 , -0.13162509, -0.14493116],
        [ 0.28283886, -0.36243248, -0.09016212,  0.33943296, -0.28686068,
          0.35715365,  0.21762434, -0.15938887, -0.22994086, -0.06826481],
        [-0.38092239, -0.4000077 ,  0.42814942, -0.07400593, -0.37057818,
          0.19777655, -0.26676063,  0.49937126,  0.38224672, -0.01526912],
        [ 0.04026271,  0.02317278,  0.16878569,  0.13316044, -0.15362837,
          0.21938336, -0.31632438,  0.09086793,  0.20765193, -0.4133321 ],
        [ 0.18160249, -0.25692881,  0.34517759, -0.37601489,  0.13074374,
         -0.04497059,  0.2053323

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
X.mean(), X.var()

(5.020592800278595, 3.7736598583625054)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [18]:
## your code
x = np.arange(5)
x = (x+x.reshape(5,1)) % 5
x

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    vals = s * np.random.random(c)
    res = np.argmin((np.cumsum(x) <= vals.reshape(-1, 1)), axis=1)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

array([4, 4, 0, 0, 0], dtype=int64)

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
## your code