In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
## your code
pows = np.arange(1, 21)
ans = (2 * np.ones((20,)))**pows / pows
ans

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
## your code
n = 5
pow1 = 3*np.arange(1, n + 1)
pow2 = 4*np.arange(1, n + 1)
np.sum((0.1 * np.ones((n,)))**pow1 * (0.2 * np.ones((n,))) ** pow2)

1.6000025600040968e-06

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
## your code
z = np.zeros((8, 8))
o = np.arange(0, 8, 2)
c = np.arange(1, 8, 2)
z[o, :] = np.arange(0, 8) % 2
z[c, :] = np.arange(1, 9) % 2
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [17]:
X = np.random.random((5, 2))

## your code
r = np.sum(X ** 2, axis=1) ** 0.5
X[:,1] = np.arcsin(X[:,1]/r)
X[:,0] = r
X

array([[0.39234978, 1.43480666],
       [1.01188698, 0.4612406 ],
       [0.58286604, 0.65503045],
       [0.78734693, 1.39970951],
       [0.83159689, 1.57005809]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
X = np.random.randint(0, 30, (10, 10))

x, y = np.where(X == X.flat[np.argmax(X)])
list(zip(x,y)), X

([(0, 0), (0, 2), (3, 2), (6, 4), (8, 4)],
 array([[29, 26, 29,  3, 27,  6,  1,  5,  1,  6],
        [ 4,  3, 16, 24,  7,  0, 16,  3, 26,  9],
        [27,  2, 19, 17, 13, 15, 20, 10, 23,  6],
        [18,  9, 29, 20, 23, 28, 16,  8, 26,  7],
        [23, 11, 14, 28,  8,  1, 20, 16, 17, 23],
        [20, 20, 27, 18, 28,  4,  7, 13,  0,  8],
        [22, 10, 13,  4, 29,  4, 14,  4, 27, 10],
        [11,  6, 24,  6,  6, 27, 21, 19, 13,  5],
        [ 7, 23, 13, 16, 29, 11, 17,  2,  0, 20],
        [22, 10, 17, 24, 22, 27, 15,  2,  5, 13]]))

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [8]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X, y, X[np.argmin(np.sum((X-y) ** 2, axis=1)), :]

(array([[0.84179781, 0.43275433],
        [0.27066565, 0.44204882],
        [0.24574531, 0.74822857],
        [0.93127569, 0.62078345],
        [0.5736767 , 0.6053585 ],
        [0.83461991, 0.45401702],
        [0.15687998, 0.8424322 ],
        [0.93403752, 0.83232288],
        [0.37080682, 0.61919244],
        [0.75754745, 0.94027282]]),
 array([[0.85208694, 0.10572085]]),
 array([0.84179781, 0.43275433]))

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [9]:
## your code
def f(x):
    if x < 0:
        return x ** 2 + 2*x + 6
    if 0 <= x <= 2:
        return x  + 6
    if x >= 2:
        return x ** 2 + 4*x-4

x = np.linspace(-3, 3, 100)

list(map(f, x))

[9.0,
 8.761248852157943,
 8.529843893480258,
 8.305785123966942,
 8.089072543617998,
 7.879706152433425,
 7.677685950413223,
 7.483011937557392,
 7.295684113865932,
 7.115702479338843,
 6.943067033976125,
 6.777777777777777,
 6.619834710743801,
 6.469237832874196,
 6.325987144168962,
 6.190082644628099,
 6.061524334251607,
 5.940312213039485,
 5.8264462809917354,
 5.719926538108356,
 5.620752984389348,
 5.528925619834711,
 5.444444444444445,
 5.367309458218549,
 5.297520661157025,
 5.235078053259871,
 5.179981634527089,
 5.132231404958677,
 5.0918273645546375,
 5.058769513314968,
 5.033057851239669,
 5.014692378328742,
 5.003673094582186,
 5.0,
 5.003673094582186,
 5.014692378328742,
 5.033057851239669,
 5.058769513314968,
 5.0918273645546375,
 5.132231404958678,
 5.179981634527089,
 5.235078053259872,
 5.297520661157025,
 5.367309458218549,
 5.444444444444445,
 5.528925619834711,
 5.620752984389348,
 5.719926538108356,
 5.8264462809917354,
 5.940312213039486,
 6.03030303030303,
 6.09

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [10]:
X = np.random.random((10, 10))

(X.T - X.mean(axis=1)).T, (X.T - X.mean(axis=1)).T.mean(axis=1)

(array([[-0.16871465,  0.15214243, -0.0022576 ,  0.39605396,  0.210461  ,
         -0.08458584, -0.2075607 ,  0.12145881, -0.11858879, -0.29840862],
        [-0.48735216, -0.02665781,  0.49657404,  0.26155146, -0.15088111,
         -0.44891128,  0.47614992, -0.0140415 , -0.29458278,  0.18815123],
        [ 0.39876302,  0.42890905, -0.25789065,  0.4043294 , -0.34093349,
         -0.25441773,  0.07096276, -0.49181049, -0.16387759,  0.20596572],
        [ 0.43262907, -0.51191171, -0.00552985,  0.15209897,  0.22780164,
          0.41909734, -0.19725242, -0.26422855, -0.45441554,  0.20171106],
        [ 0.0411724 , -0.17357404, -0.245662  ,  0.32354908, -0.00577123,
         -0.35299613, -0.24470118,  0.3880403 , -0.11466764,  0.38461044],
        [-0.40475532,  0.32724191,  0.01079346, -0.33456091,  0.45582082,
         -0.08742534,  0.45644323,  0.16954977, -0.45093636, -0.14217127],
        [-0.30363316,  0.18528479, -0.4289801 , -0.12386383,  0.28442649,
          0.33595903,  0.4890749

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [11]:
X = np.random.normal(loc=5, scale=2., size=1000)
X.mean(), X.var()

(5.057690767460828, 4.2012583817343945)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [12]:
## your code
x = (np.arange(0, 25) % 5).reshape(5, 5)
np.roll(x, 1, axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [13]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    vals = s * np.random.random(c)
    res = np.argmin((np.cumsum(x) <= vals.reshape(-1, 1)), axis=1)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

array([0, 4, 4, 4, 4], dtype=int64)

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [14]:
## your code